#!/usr/bin/env python3
"""
================================================================================
 BRAM Initialization File Generator for Pre-Scaled Cube Root Lookup
================================================================================
Paper:  An Ultra-Low Resource FPGA Architecture for Cube Root Computation
        Using Pre-Scaled BRAM Lookup
Module: cube_root_bram_ultra_3cyc

Generates the 384 x 24-bit pre-scaled BRAM contents according to:
    T_r[i] = round(2^n' * cbrt(y_{r,i}))
where:
    y_{r,i} = L_r + (i + 0.5)/N * W_r       
    L_r = W_r = 2^(k_0 + r),  k_0 = -1
    N = 128, R = 3, n' = 23 (Q1.23 output)

The pre-scaling factor (2^((k_0+r)/3)) is implicitly embedded in cbrt(y_{r,i})
since cbrt(L_r * y_hat) = cbrt(L_r) * cbrt(y_hat) = 2^((k_0+r)/3) * cbrt(y_hat),
so storing cbrt(y_{r,i}) directly already includes the scaling factor.

Outputs:
    1) bram_init.mem    : Verilog $readmemh format, one hex per line
    2) bram_init.coe    : Xilinx Block Memory Generator COE format
    3) bram_inline.txt  : Inline Verilog assignments (for embedding in RTL)

Usage:
    python3 gen_bram_init.py
================================================================================
"""

import math

# -----------------------------------------------------------------------------
# Design parameters 
# -----------------------------------------------------------------------------
WIDTH       = 24                # output word width (Q1.23)
N_FRAC_OUT  = 23                # output fractional bits (n')
R           = 3                 # number of sub-intervals
N_PER_RANGE = 128               # samples per sub-interval (b = 7)
K0          = -1                # base exponent k_0
TOTAL       = R * N_PER_RANGE   # 384 entries
MASK        = (1 << WIDTH) - 1  # 24-bit mask

# -----------------------------------------------------------------------------
# Compute table contents
# -----------------------------------------------------------------------------
def compute_table():
    """Generate 384 pre-scaled cube root values"""
    table = []
    for r in range(R):
        Lr = 2.0 ** (K0 + r)         # lower bound of D_r
        Wr = Lr                      # interval width = lower bound (since L_r=W_r)
        for i in range(N_PER_RANGE):
            # Midpoint sampling, Eq. (5)
            y_ri = Lr + (i + 0.5) / N_PER_RANGE * Wr
            cbrt_val = y_ri ** (1.0 / 3.0)
            # Pre-scaled fixed-point quantization,
            T = int(round(cbrt_val * (1 << N_FRAC_OUT)))
            T &= MASK                # ensure 24-bit
            table.append(T)
    assert len(table) == TOTAL
    return table


# -----------------------------------------------------------------------------
# Output formats
# -----------------------------------------------------------------------------
def write_mem(table, fname):
    """Verilog $readmemh format."""
    with open(fname, "w") as f:
        f.write("// BRAM initialization for cube_root_bram_ultra_3cyc\n")
        f.write("// 384 x 24-bit pre-scaled cube root values\n")
        f.write("// Generated by gen_bram_init.py\n")
        for i, v in enumerate(table):
            f.write(f"{v:06x}    // entry {i}\n")
    print(f"  wrote {fname}")


def write_coe(table, fname):
    """Xilinx Block Memory Generator COE format."""
    with open(fname, "w") as f:
        f.write("; COE file for Xilinx Block Memory Generator\n")
        f.write("; 384 x 24-bit pre-scaled cube root LUT\n")
        f.write("memory_initialization_radix=16;\n")
        f.write("memory_initialization_vector=\n")
        lines = [f"{v:06x}" for v in table]
        f.write(",\n".join(lines) + ";\n")
    print(f"  wrote {fname}")


def write_inline(table, fname):
    """Inline Verilog assignments for embedding in RTL."""
    with open(fname, "w") as f:
        f.write("// Inline initialization block for cube_root_bram_ultra_3cyc\n")
        f.write("// Paste inside `initial begin ... end`\n")
        f.write("initial begin\n")
        for r in range(R):
            f.write(f"    // Range {r}: y in [{2.0**(K0+r):.2f}, {2.0**(K0+r+1):.2f})\n")
            base = r * N_PER_RANGE
            for row_start in range(0, N_PER_RANGE, 4):
                line = "    "
                for k in range(4):
                    idx = base + row_start + k
                    line += f"bram[{idx:3d}] = 24'h{table[idx]:06X}; "
                f.write(line.rstrip() + "\n")
        f.write("end\n")
    print(f"  wrote {fname}")


# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------
def verify(table):
    """Check max relative error matches the paper's reported 0.13%."""
    print("\n--- Verification ---")
    max_rel = 0.0
    sum_rel = 0.0
    n_pts = 0
    # Test at every sampling midpoint (worst case is at left endpoints)
    for r in range(R):
        Lr = 2.0 ** (K0 + r)
        Wr = Lr
        # Test at left endpoint of each cell (worst case)
        for i in range(N_PER_RANGE):
            y_left = Lr + i / N_PER_RANGE * Wr
            ideal = y_left ** (1.0 / 3.0)
            stored = table[r * N_PER_RANGE + i] / (1 << N_FRAC_OUT)
            rel = abs(stored - ideal) / ideal
            max_rel = max(max_rel, rel)
            sum_rel += rel
            n_pts += 1
    avg_rel = sum_rel / n_pts
    p_eff = -math.log2(max_rel) if max_rel > 0 else float('inf')
    print(f"  Test points       : {n_pts}")
    print(f"  Max relative error: {max_rel*100:.4f}% (paper: 0.13%)")
    print(f"  Avg relative error: {avg_rel*100:.4f}%")
    print(f"  Effective precision: {p_eff:.2f} bits (paper: 9.6)")


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    print("=== Pre-Scaled BRAM Initialization Generator ===")
    print(f"  R={R}, N={N_PER_RANGE}, total={TOTAL} entries, width={WIDTH} bits")
    table = compute_table()
    print(f"  Generated {len(table)} entries.\n")
    print("--- Outputs ---")
    write_mem(table, "bram_init.mem")
    write_coe(table, "bram_init.coe")
    write_inline(table, "bram_inline.txt")
    verify(table)
    print("\nDone.")
